"""Initial migration - LPR database schema

Revision ID: a9c864ed58e0
Revises: 
Create Date: 2025-08-12 07:23:02.909668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c864ed58e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cameras', 'brand',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('cameras', 'model',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('cameras', 'last_test_result',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index('idx_camera_camera_id', 'cameras', ['camera_id'], unique=False)
    op.alter_column('detections', 'group_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('detections', 'duplicate_of',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('detections', 'track_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('detections', 'ocr_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('idx_detections_best_shot'), table_name='detections')
    op.drop_index(op.f('idx_detections_group_id'), table_name='detections')
    op.drop_index(op.f('idx_detections_plate_camera'), table_name='detections')
    op.drop_index(op.f('idx_detections_track_id'), table_name='detections')
    op.create_index('idx_detection_camera_time', 'detections', ['camera_id', 'detected_at'], unique=False)
    op.alter_column('video_recordings', 'filename',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.create_index('idx_video_recording_camera_time', 'video_recordings', ['camera_id', 'start_time'], unique=False)
    op.create_index('idx_video_recording_date', 'video_recordings', ['start_time'], unique=False)
    op.create_index('idx_video_recording_filename', 'video_recordings', ['filename'], unique=False)
    op.create_unique_constraint(None, 'video_recordings', ['filename'])
    op.drop_column('video_recordings', 'fps')
    op.drop_column('video_recordings', 'file_size_mb')
    op.drop_column('video_recordings', 'format')
    op.drop_column('video_recordings', 'resolution')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_recordings', sa.Column('resolution', sa.VARCHAR(length=20), nullable=True))
    op.add_column('video_recordings', sa.Column('format', sa.VARCHAR(length=20), nullable=True))
    op.add_column('video_recordings', sa.Column('file_size_mb', sa.FLOAT(), nullable=True))
    op.add_column('video_recordings', sa.Column('fps', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'video_recordings', type_='unique')
    op.drop_index('idx_video_recording_filename', table_name='video_recordings')
    op.drop_index('idx_video_recording_date', table_name='video_recordings')
    op.drop_index('idx_video_recording_camera_time', table_name='video_recordings')
    op.alter_column('video_recordings', 'filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index('idx_detection_camera_time', table_name='detections')
    op.create_index(op.f('idx_detections_track_id'), 'detections', ['track_id'], unique=False)
    op.create_index(op.f('idx_detections_plate_camera'), 'detections', ['plate_text', 'camera_id', 'detected_at'], unique=False)
    op.create_index(op.f('idx_detections_group_id'), 'detections', ['group_id'], unique=False)
    op.create_index(op.f('idx_detections_best_shot'), 'detections', ['is_best_shot'], unique=False)
    op.alter_column('detections', 'ocr_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('detections', 'track_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('detections', 'duplicate_of',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('detections', 'group_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index('idx_camera_camera_id', table_name='cameras')
    op.alter_column('cameras', 'last_test_result',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('cameras', 'model',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('cameras', 'brand',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
